name: ai_webchat
description: Cross-platform chat client with registration and split-view inbox.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  characters: ^1.3.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
